FROM ubuntu:latest
LABEL authors="tersoman"

ENTRYPOINT ["top", "-b"]

#FROM node:14
#COPY . /app
#WORKDIR /app
#RUN npm install
#CMD ["npm", "start"]


## İmage olarak Node.js'in son sürümünü kullan
#FROM node:14
#
## Çalışma dizini oluştur
#WORKDIR /usr/src/app
#
## Gerekli bağımlılıkları kopyala ve kur
#COPY package*.json ./
#RUN npm install
#
## Uygulama kodunu kopyala
#COPY . .
#
## Uygulamayı çalıştır
#CMD ["npm", "start"]
