#LABEL authors="tersoman"
FROM node:20.12-alpine3.18 AS build_stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:alpine
WORKDIR /app
COPY --from=build_stage /app/build .
RUN npm install -g http-server
EXPOSE 3000
CMD ["http-server", "-p", "3000"]

# docker build --tag frontend/test/1 --file Dockerfile_frontend .
