#LABEL authors="tersoman"
FROM node:20.12-alpine3.18 AS build_stage

ENV http_proxy=http://localhost:8080

WORKDIR /app

COPY package*.json ./

RUN npm config set proxy http://localhost:8080

RUN npm install

COPY . .

RUN npm run build

FROM node:alpine

WORKDIR /app

COPY --from=build_stage /app/build .

RUN npm install -g http-server

EXPOSE 3000

CMD ["http-server", "-p", "3000"]

#FROM node:14
#COPY . /app
#WORKDIR /app
#RUN npm install
#CMD ["npm", "start"]
