version: '3'
services:
  frontend:
    build:
      context: ../client/client
      dockerfile: Dockerfile_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ../core
      dockerfile: Dockerfile_backend
    ports:
      - "8080:8080"

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=project'
      - 'MYSQL_ALLOW_EMPTY_PASSWORD=true'
    ports:
      - '3306'


  my_script:
    build:
      context: .
      dockerfile: Dockerfile_script
    environment:
      LATITUDE: ${LATITUDE}
      LONGITUDE: ${LONGITUDE}
      INTENSITY: ${INTENSITY}
# docker-compose run --env LATITUDE=50 --env LONGITUDE=60 --env INTENSITY=70 my_script
# docker-compose restart my_script
#docker-compose stop my_script sonsuz donguden cikmak icin tekrar baslatmak icin restart
#docker-compose up -d my_script
# docker-compose down

#  jobmanager:
#    image: flink:latest
#    expose:
#      - "6123"
#    ports:
#      - "8081:8081"
#    command: jobmanager
#
#  taskmanager:
#    image: flink:latest
#    expose:
#      - "6121"
#    command: taskmanager
#    depends_on:
#      - jobmanager
