FROM eclipse-temurin:21.0.1_12-jdk
WORKDIR /app
COPY build/libs/core-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]

#docker build --tag backend/test/1 --file Dockerfile_backend .
#docker run -p 8080:8080 backend/test/1

#docker build -t your-image-name .
#docker run -p 3000:3000 your-image-name
#docker run your-image-name
#docker-compose up
#pause, down (remove) , ps (status), logs, exec
