FROM python:3.9-alpine

ENV GROUP_ID=1000 \
    USER_ID=1000 \
    PYTHONUNBUFFERED=1

RUN apk update \
    && apk add python3 py3-pip \
    && python3 -m venv /venv \
    && /venv/bin/pip install requests \
    && /venv/bin/pip install python-dotenv

WORKDIR /app
COPY scripts/ /app/scripts/

CMD ["/venv/bin/python3", "/app/scripts/script.py"]